* Encoding: UTF-8.
*DETROIT RESIDENTIAL MODEL FOR NE AREA
*FILE BUILT IN MSACCESS AND IMPORTED AS EXCEL FILE. 

FREQUENCIES CCD.
FREQUENCIES ECF.

*******************************
*ADD ECF FILTERS HERE IF NECESSARY.
*******************************

*RECORD STARTING NUMBER OF RECORDS.
* # records




 ******************************************************************************
 *CREATE PRICE CATEGORIES.
 ******************************************************************************
*USEFUL FOR EXAMINING RATIOS STRATIFIED BY PRICE.
*Use natural breaks for entire sales inventory, not just this model. Update when new Citywide sales file is created.

FREQUENCIES SALEPRICE.
COMPUTE PRICECLASS = 0.

*CUT POINTS: 48000 67000 94000 134000.

COMPUTE PRICECLASS = 0.
IF (SALEPRICE LT 48000) PRICECLASS=1.
IF (SALEPRICE GE 48000) AND (SALEPRICE LT 67000) PRICECLASS=2.
IF (SALEPRICE GE 67000) AND (SALEPRICE LT 94000) PRICECLASS=3.
IF (SALEPRICE GE 94000) AND (SALEPRICE LT 134000) PRICECLASS=4.
IF (SALEPRICE GE 134000) PRICECLASS=5.

VALUE LABELS PRICECLASS
1 'Below 48000'
2 '48000 to 67000'
3 '67000 to 94000'
4 '94000 to 134000'
5 '134000 +'.

CROSSTABS PRICECLASS BY sRESB_STYLE.
FREQUENCIES PRICECLASS.


 ******************************************************************************
*RECORD FILTERING
*******************************************************************************

COMPUTE IN=0.

FREQUENCIES Sresb_style.
CROSSTABS Sresb_style BY Spropclass.

FREQUENCIES SPROPCLASS. 

CROSSTABS SRESB_STYHGT BY SRESB_STYLE.

IF (Sresb_style='SINGLE FAMILY') IN=1.
IF (Sresb_style='1/2 DUPLEX') IN=1.
IF (Sresb_style='ROW HOUSE')  IN=1.

FREQUENCIES IN.
* # RECORDS.

SELECT IF (IN=1).

***************

*We will create a field called 'OUT' and use it to fiter out records with bad data.

COMPUTE OUT=0.

*FILTER OUT LOTS THAT ARE TOO SMALL.
IF (sTOTALSQFT<400) OUT=1.

*FILTER OUT BUILDINGS  THAT ARE TOO SMALL OR TOO LARGE.
*NO BLDSF ERRORS.
IF (Sresb_floorarea <400) OUT=1.

*FILTER OUT PRCES THAT ARE TOO LOW. 10,000 was chosen as a reasonable minimum.
 IF (SALEPRICE < 10000) OUT=1.

 FREQ OUT.
*Removes # records.
SELECT IF OUT = 0.
* # records. 


 ***************

* Identify Duplicate Cases.
*If there is a field that uniquely identifies each record, assign the last instance 
as the primary record, and all other instances as duplicates.
*You may need to build a field that uniquely identifies each record (KEY).
*Select only the primary records. 


SORT CASES BY PARCELNO(A) SALEPRICE(A) saledate(A). 
MATCH FILES 
  /FILE=* 
  /BY PARCELNO SALEPRICE saledate 
  /FIRST=PrimaryFirst 
  /LAST=PrimaryLast. 
DO IF (PrimaryFirst). 
COMPUTE  MatchSequence=1-PrimaryLast. 
ELSE. 
COMPUTE  MatchSequence=MatchSequence+1. 
END IF. 
LEAVE  MatchSequence. 
FORMATS  MatchSequence (f7). 
COMPUTE  InDupGrp=MatchSequence>0. 
SORT CASES InDupGrp(D). 
MATCH FILES 
  /FILE=* 
  /DROP=PrimaryFirst InDupGrp MatchSequence. 
VARIABLE LABELS  PrimaryLast 'Indicator of each last matching case as Primary'. 
VALUE LABELS  PrimaryLast 0 'Duplicate Case' 1 'Primary Case'. 
VARIABLE LEVEL  PrimaryLast (ORDINAL). 
FREQUENCIES VARIABLES=PrimaryLast.
SELECT IF PrimaryLast= 1. 
*# duplicates. 
*# Unique SALES. 


***************

*Eliminate transactions where price is close to assessment (non-market sale).
COMPUTE PRICEISASMT_RATIO = AVWHENSOLD / SALEPRICE.
COMPUTE PRICEISASMT_RATIO2 = PRICEISASMT_RATIO.
IF (PRICEISASMT_RATIO>=.90 AND PRICEISASMT_RATIO<=1.1) PRICEISASMT_RATIO2=1.
GRAPH/SCATTER = PRICEISASMT_RATIO2 WITH SALEPRICE.

COMPUTE PRICEISASMT_RATIO = PRICEISASMT_RATIO2.

COMPUTE PRICEISASMT = 1.
 IF (PRICEISASMT_RATIO=1) PRICEISASMT = 0.
FREQ PRICEISASMT.
SELECT IF PRICEISASMT=1.
*REMOVED # RECORDS, # TOTAL.


 ******************************************************************************
*EXPLORATORIES.
*******************************************************************************
*Look for zero values or other errors and make notes on any corrections made. 

FREQUENCIES Sresb_floorarea.
MEANS sRESB_FLOORAREA/CELLS MEAN MEDIAN MIN MAX RANGE.
*median is #.

FREQUENCIES Sresb_groundarea.
MEANS Sresb_groundarea/CELLS MEAN MEDIAN MIN MAX RANGE.
*Median is #.

 FREQ sTOTALSQFT. 
MEANS sTOTALSQFT/CELLS MEAN MEDIAN MIN MAX RANGE.
*Median is #.

FREQUENCIES Sresb_styhgt.
*0 -1 are 1 story.
*2 - 5 are 2 story.

 FREQUENCIES sREB_GARTYPE.
*OK.

COMPUTE IN=0.
IF (Sresb_garagearea>0) IN=1.
FREQUENCIES IN.
FILTER BY IN.
MEANS Sresb_garagearea/CELLS MEAN MEDIAN MINIMUM MAX RANGE.
*MEDIAN IS #.
FREQUENCIES  Sresb_garagearea.
FILTER off. 

 FREQUENCIES Sresb_yearbuilt.
*OK.

 FREQUENCIES Sresb_heat.
*OK.

FREQUENCIES SCOND.
*OK.

 FREQUENCIES Sresb_fullbaths.
*OK.

FREQUENCIES Sresb_halfbaths.
*OK.
 
FREQUENCIES Sresb_fireplace.
*OK.

 FREQUENCIES Sresb_basementarea.
*OK. 
 
FREQUENCIES RD_CLASS.


*******************************************************************************.
*SETUP CALCULATIONS
*******************************************************************************

*Calculate sales ratio.
COMPUTE RATIO=SESTTCV/SALEPRICE.
FREQUENCIES RATIO.
MEANS RATIO/CELLS MEAN MEDIAN MINIMUM MAX RANGE.
*MEDIAN #.


*CREATE SALE PRICE PER SF FIELD, WHICH WILL BE USED THROUGHOUT THE REST OF THE SCRIPT.
COMPUTE SPPSF = SALEPRICE/Sresb_floorarea.
MEANS SPPSF/CELLS MEAN MEDIAN MIN MAX RANGE.
*Median is $#.



*******************************************************************************
*CATEGORICAL BINARY TRANSFORMATIONS.
*******************************************************************************
*COMMENT OUT BINARY VALUABLES THAT WILL NOT BE USED. COMBINE VARIABLES THAT DO NOT HAVE ENOUGH SALES (<7).
*NOTE BASE, EXCEPT WHERE CONSTANT. COMMENT OUT BASE VARIABLE TO GO WITH THE CONSTANT.

*PROPERTY TYPE.

VALUE LABELS sRESB_STYHGT    
0 '1 story'
1 '1+ story'
2 '1.25 story'
3 '1.5 story'
4 '1.75 story'
5 '2 story'
6 '2.5 story'
7 '3 story'
8 '3.5 story'
9 'Bi-level split'
10 'Tri-level split'.

FREQ Sresb_style.
FREQ Sresb_styhgt. 
CROSSTABS Sresb_styhgt BY Sresb_style.

COMPUTE ONESTORY=0.
COMPUTE TWOSTORY=0.
COMPUTE TWOPLUSSTORY=0.
COMPUTE BILEVELSPLIT=0.
IF (Sresb_styhgt LE 2) ONESTORY = 1.
IF (Sresb_styhgt GT 2) AND (Sresb_styhgt LE 5) TWOSTORY = 1.
IF (Sresb_styhgt GT 5) AND (Sresb_styhgt LE 8)TWOPLUSSTORY = 1.
IF (Sresb_styhgt GT 8) AND (Sresb_styhgt LE 10)BILEVELSPLIT = 1.
COMPUTE CHECK=SUM(ONESTORY TO TWOSTORY). 
FREQUENCIES ONESTORY TO TWOSTORY.

 CROSSTABS Sresb_style BY CHECK.
 CROSSTABS Sresb_style BY ONESTORY.
 CROSSTABS Sresb_style BY TWOSTORY.
 CROSSTABS Sresb_style BY TWOPLUSSTORY.
 CROSSTABS Sresb_style BY BILEVELSPLIT.

COMPUTE SINGLE_FAMILY1STORY = 0.
COMPUTE SINGLE_FAMILY2STORY = 0.
COMPUTE SINGLE_FAMILY2PLUSSTORY = 0.
COMPUTE SINGLE_FAMILYBILEVELSPLIT = 0.
COMPUTE HALF_DUPLEX1STORY = 0.
COMPUTE HALF_DUPLEX2STORY = 0.
COMPUTE HALF_DUPLEX2PLUSSTORY = 0.
COMPUTE ROW_HOUSE1STORY = 0.
COMPUTE ROW_HOUSE2STORY = 0.
COMPUTE ROW_HOUSE2PLUSSTORY = 0.

* RUN BLOCK, DETERMINE BASE, DELETE VARIABLES FROM DATA FILE, COMMENT OUT BASE AND RERUN.
* #### IS BASE.
IF (Sresb_style='SINGLE FAMILY') AND (ONESTORY=1) SINGLE_FAMILY1STORY=1.
IF (Sresb_style='SINGLE FAMILY') AND (TWOSTORY=1) SINGLE_FAMILY2STORY=1.
IF (Sresb_style='SINGLE FAMILY') AND (TWOPLUSSTORY=1) SINGLE_FAMILYPLUSSTORY=1.
IF (Sresb_style='SINGLE FAMILY') AND (BILEVELSPLIT=1) SINGLE_FAMILYBILEVELSPLIT=1.
IF (Sresb_style='1/2 DUPLEX') AND (ONESTORY=1) HALF_DUPLEX1STORY=1.
IF (Sresb_style='1/2 DUPLEX') AND (TWOSTORY=1) HALF_DUPLEX2STORY=1.
IF (Sresb_style='1/2 DUPLEX') AND (TWOPLUSSTORY=1) HALF_DUPLEX2PLUSSTORY=1.
IF (Sresb_style='ROW HOUSE') AND (ONESTORY=1) ROW_HOUSE1STORY=1.
IF (Sresb_style='ROW HOUSE') AND (TWOSTORY=1) ROW_HOUSE2STORY=1.
IF (Sresb_style='ROW HOUSE') AND (TWOPLUSSTORY=1) ROW_HOUSE2PLUSSTORY=1.

FREQUENCIES SINGLE_FAMILY1STORY TO HALF_DUPLEX2STORY.
*Note combined variables here.

***************
*BUILDING ERAS.

*Convert YearBuilt into TimePeriods.
*Time periods based on significant divisions of development eras.

*BUCKETS FOR ENTIRE INVENTORY (4/2023-3/2025):
    PRE 1910 1.8%
    1910 TO 1929 23.9%
    1930 TO 1945 36.6%
    1946 TO 1960 35.1%
    1961 TO 1990 1.8%
    POST 1990 0.8%.

COMPUTE ERABUILT=0.

 VALUE LABELS ERABUILT   
1 'Pre 1910'
2 '1910-1929'
3 '1930-1945'
4 '1946-1960'
5 '1961-1990'
6 'Post 1990'.

IF (Sresb_yearbuilt LT 1910) ERABUILT=1.
IF (Sresb_yearbuilt GE 1910) AND (Sresb_yearbuilt LT 1930) ERABUILT=2.
IF (Sresb_yearbuilt GE 1930) AND (Sresb_yearbuilt LT 1946) ERABUILT=3.
IF (Sresb_yearbuilt GE 1946) AND (Sresb_yearbuilt LT 1961) ERABUILT=4.
IF (Sresb_yearbuilt GE 1961) AND (Sresb_yearbuilt LE 1990) ERABUILT=5.
IF (Sresb_yearbuilt GT 1990) ERABUILT=6.
FREQUENCIES ERABUILT.

*Recode Erabuilt into binaries. 
*# is base.
RECODE ERABUILT (1=1)(ELSE=0) INTO YB_PRE_1910.
RECODE ERABUILT (1 2=1)(ELSE=0) INTO YB_PRE_1929.
RECODE ERABUILT (3=1)(ELSE=0) INTO YB_1930_TO1945.
RECODE ERABUILT (4=1)(ELSE=0) INTO YB_1946_TO_1960.
RECODE ERABUILT (5 6=1)(ELSE=0) INTO YB_POST_1961.
ECODE ERABUILT (6=1)(ELSE=0) INTO YB_POST_1990.

FREQUENCIES YB_PRE_1929 TO YB_POST_1961.
*Note combined variables here.


***************
*CONDITION CODE.
FREQUENCIES SCOND.

 VALUE LABELS SCOND 
0 'Excellent'
1 'Very Good'
2 'Good'
3 'Average'
4 'Fair'
5 'Poor'
 6 'Very Poor' 
 7 'Unsound'.

CROSSTABS ERABUILT BY SCOND.
MEANS SPPSF BY SCOND/CELLS=COUNT MEDIAN MEAN MIN MAX.

*SCOND # IS THE BASE. MISSING TREATED AS BASE.

RECODE SCOND (0=1)(ELSE=0) INTO EXCELLENT.
RECODE SCOND (1=1)(ELSE=0) INTO VERY_GOOD.
RECODE SCOND (2=1)(ELSE=0) INTO GOOD.
RECODE SCOND (3=1)(ELSE=0) INTO AVG.
RECODE SCOND (4=1)(ELSE=0) INTO FAIR.
RECODE SCOND (5=1)(ELSE=0) INTO POOR.
RECODE SCOND (6 7=1)(ELSE=0) INTO VERY_POOR_UNSOUND.
RECODE SCOND (7=1)(ELSE=0) INTO UNSOUND.

FREQUENCIES GOOD TO VERY_POOR_UNSOUND.  
*Note combined variables here.

***************
*BATHROOMS.

FREQUENCIES Sresb_fullbaths.
FREQUENCIES Sresb_halfbaths.

*ONE_BATH IS BASE.

RECODE Sresb_fullbaths (1=1)(ELSE=0)INTO ONE_BATH.
RECODE Sresb_fullbaths (2=1) (ELSE=0)INTO TWO_BATHS.
RECODE Sresb_fullbaths (2 3 4 5 6 7 8 9 10=1) (ELSE=0)INTO TWO_PLUS_BATHS.
RECODE Sresb_halfbaths (1 2 3 4 5=1) (ELSE=0)INTO POWDER_ROOM.

FREQUENCIES TWO_PLUS_BATHS TO POWDER_ROOM.
*Note combined variables here.

***************
FIREPLACES.

*BASE IS ALWAYS NO FIREPLACE.
 
FREQUENCIES Sresb_fireplace.
RECODE Sresb_fireplace(1 2 3 4 5 6 =1)(ELSE=0) INTO FIREPLACE.

FREQUENCIES FIREPLACE. 
* # CASES.


***************
*BASEMENTS.

FREQ sRESB_CRAWSPACE.
FREQ sRESB_SLABAREA.
FREQ sRESB_BASEMENTAREA.

COMPUTE PCTCRAWL=(sRESB_CRAWSPACE/SRESB_GROUNDAREA).
COMPUTE PCTSLAB=(sRESB_SLABAREA/SRESB_GROUNDAREA).
COMPUTE PCTBSMNT=(sRESB_BASEMENTAREA/SRESB_GROUNDAREA).

*BASEMENT IS ALWAYS BASE.

COMPUTE CRAWL = 0.
IF (PCTCRAWL GT PCTBSMNT) AND (PCTCRAWL GT PCTSLAB) CRAWL =1.
*CRAWL FREQUENCY #. 

COMPUTE SLAB = 0.
IF (PCTSLAB GT PCTCRAWL) AND (PCTSLAB GT PCTBSMNT) SLAB =1.
*SLAB FREQUENCY #.
 
FREQUENCIES CRAWL SLAB.


***************
*BUILDING CLASS (QUALITY)

VALUE LABELS Sresb_bldgclass 
5 '5: A'
4 '4: B'
3 '3: BC'
2 '2: C'
1 '1: CD'
0 '0: D'.

FREQ Sresb_bldgclass.
*2 (C) IS BASE.

RECODE Sresb_bldgclass (5=1)(ELSE=0) INTO QBEST.
RECODE Sresb_bldgclass (3 4 5=1)(ELSE=0) INTO QABOVE_AVG.
RECODE Sresb_bldgclass (0 1=1)(ELSE=0) INTO QBELOW_AVG.
RECODE Sresb_bldgclass (0=1)(ELSE=0) INTO QPOOR.

*Combined 3 4 & 5 as QABOVE_AVG.

FREQUENCIES QABOVE_AVG TO QBELOW_AVG.
*Note combined variables here.


***************
*GARAGES.

*PRESENCE OF GARAGE (Y/N).
COMPUTE GARAGE=0.
IF (SRESB_GARAGEAREA GE 200) GARAGE=1. 
FREQUENCIES GARAGE.
* # GARAGES.


*?????????????????????????????????????
*ARE WE USING THIS???????.
*GARAGE TYPE.
CROSSTABS GARAGE BY Sreb_garType.
*NO GARAGE IS BASE.
RECODE sREB_GARTYPE (1=1)(ELSE=0) INTO ONE_CAR_GARAGE.
RECODE sREB_GARTYPE (2=1)(ELSE=0) INTO TWO_CAR_GARAGE.
FREQUENCIES ONE_CAR_GARAGE TWO_CAR_GARAGE.

*?????????????????????????????????????.


*GARAGE SPACES. 
 FREQUENCIES Sresb_garagearea.
COMPUTE GARAGESPACES = 0.
IF (Sresb_garagearea GT 200) AND (Sresb_garagearea LT 420) GARAGESPACES = 1.
IF (Sresb_garagearea GT 419) AND (Sresb_garagearea LT 600) GARAGESPACES = 2.
IF (Sresb_garagearea GT 599) AND (Sresb_garagearea LT 820) GARAGESPACES = 3.
IF (Sresb_garagearea GT 819) GARAGESPACES = 4.

CROSSTABS GARAGE BY GARAGESPACES.

COMPUTE LN_GARAGESPACES=LN(GARAGESPACES).



***************
*ROAD CLASS 

FREQUENCIES RD_CLASS.

*simple binary - Arterial vs all others as base.
 RECODE RD_CLASS ('A21' 'A31' =1)(ELSE=0) INTO ARTERIAL.

FREQUENCIES ARTERIAL.


***************
*HEATING COOLING.

VALUE LABELS sRESB_HEAT
0 '0: Forced Air w/o ducts'
1 '1: Forced Air w/ ducts'
2 '2: Forced Hot Water'
3 '3: Electric Baseboard'
4 '4: Electric Ceiling Radiant'
5 '5: Radiant (in-Floor)'
6 '6: Electric Wall'
7 '7: Space Heater'
8 '8: Wall/Floor Furnace'
9 '9: Forced Heat & Cool'.

FREQUENCIES Sresb_heat.
*### IS BASE

RECODE Sresb_heat (0 1 9=1)(ELSE=0) INTO FORCED_AIR.
RECODE Sresb_heat (2=1)(ELSE=0) INTO HOT_WATER.
RECODE Sresb_heat (3=1)(ELSE=0) INTO  ELEC_BASEBOARD.
RECODE Sresb_heat (4=1)(ELSE=0) INTO  ELEC_RADIANT.
RECODE Sresb_heat (5=1)(ELSE=0) INTO  RADIANT_FLOOR.
RECODE Sresb_heat (6=1)(ELSE=0) INTO  ELEC_WALL.
RECODE Sresb_heat (7=1)(ELSE=0) INTO  SPACE_HEATER.
RECODE Sresb_heat (6 8=1)(ELSE=0) INTO  WALL.
RECODE Sresb_heat (9=1)(ELSE=0) INTO CENTRAL_AIR.

FREQUENCIES HOT_WATER TO CENTRAL_AIR.
*Note combined variables here.

***************
*BUILDING SIZE.

 FREQUENCIES sRESB_FLOORAREA.
*DISTRIBUTION BASED ON THE ENTIRE INVENTORY (4/2023-3/2025), NO NATURAL BREAKS
*RECALCULATE WHEN NEW SALES FILE IS CREATED
10% 830
35% 1018
65% 1266
90% 1659.

COMPUTE SIZE = 0.
IF (sRESB_FLOORAREA LT 830) SIZE=1. 
IF (sRESB_FLOORAREA GE 830) AND (sRESB_FLOORAREA LT 1018) SIZE=2. 
IF (sRESB_FLOORAREA GE 1018) AND (sRESB_FLOORAREA LT 12666) SIZE=3. 
IF (sRESB_FLOORAREA GE 1266) AND (sRESB_FLOORAREA LT 1659) SIZE=4. 
IF (sRESB_FLOORAREA GE 1659) SIZE=5. 
FREQUENCIES SIZE.

*(3) AVG IS ALWAYS BASE.

RECODE SIZE  (1=1)(ELSE=0) INTO SMALLEST.
RECODE SIZE  (2=1)(ELSE=0) INTO SMALL.
*RECODE SIZE  (3=1)(ELSE=0) INTO AVG.
RECODE SIZE  (4=1)(ELSE=0) INTO LARGE.
RECODE SIZE  (5=1)(ELSE=0) INTO LARGEST.

FREQUENCIES SMALLEST TO LARGEST.



***************
*TIME ANALYSES.
* Used to create Time Adjusted Sales Price variables based on changes in market trends.

COMPUTE SMONTH = XDATE.MONTH(saledate).
COMPUTE SYEAR = XDATE.YEAR(saledate).

CROSSTABS SMONTH BY SYEAR. 
COMPUTE MONTHS=0. 
IF (SYEAR=2022) MONTHS = SMONTH - 5.
IF (SYEAR=2023) MONTHS = SMONTH + 7. 
IF (SYEAR=2024) MONTHS = SMONTH + 19. 
CROSSTABS MONTHS BY SYEAR. 
*ALL MONTHS ARE REPRESENTED.
FREQ MONTHS. 


* Create time series based on average properties.
 
RECODE SCOND (4=1)(ELSE=0) INTO AVERAGE.
FILTER BY AVERAGE.
FREQUENCIES AVERAGE.
 * FREQ SCOND.
COMPUTE SPPSF=(saleprice/sRESB_FLOORAREA).
GRAPH/SCATTER=MONTHS WITH SPPSF.
MEANS SPPSF BY MONTHS/CELLS=COUNT MEDIAN MEAN.
* LOOK AT THE SCATTERPLOT AND FIT A LOESS LINE TO DETERMINE THE MONTHS WHERE
 THE SLOPE OF THE TIME LINE CHANGED.
*DEFINE SPLINE VARIABLES TO CAPTURE THE TIME PERIODS.

COMPUTE MONTHS_1TO9=MONTHS. 
IF (MONTHS>9) MONTHS_1TO9=9. 
 
COMPUTE MONTHS_10TO16=0. 
IF (MONTHS>9) MONTHS_10TO16=MONTHS-9.
IF (MONTHS>16) MONTHS_10TO16=7.

COMPUTE MONTHS_17TO24=0. 
IF (MONTHS>16) MONTHS_17TO24=MONTHS-16.
 
MEANS MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24 BY MONTHS/CELLS=MEAN. 

*CALCULATE LOG OF SALES PRICE PER SQFT (NON-LINEAR RELATIONSHIP).
COMPUTE LN_SPPSF=LN(SPPSF).

* RUN REGRESSION WITH LN_SPPSF AS DEPENDENT TO FIND TIME COEFFICIENTS.
REGRESSION
 /DEPENDENT=LN_SPPSF
 /METHOD=BACKWARD
 ARTERIAL
SINGLE_FAMILY1STORY TO HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24.
  
*COPY REGRESSION COEF INTO THE RATES FOR TIME VARIABLES.
COMPUTE RATE1 =0.
COMPUTE RATE2 =0.018824.
COMPUTE RATE3 =0.

* MAKE SURE YOU UPDATE TIME VARIABLES.
COMPUTE PRICE_INDEX = (1+RATE1)**MONTHS_1TO9* (1+RATE2)**MONTHS_10TO16* (1+RATE3)**MONTHS_17TO24.
GRAPH/SCATTER=MONTHS WITH PRICE_INDEX.

*TIME ADJUSTMENT FACTORS.
MEANS PRICE_INDEX BY MONTHS/CELLS=MEAN.

*RECORD THE VALUE FOR LAST MONTH (TARGET MONTH) AS END_INDEX.
*DON'T FORGET TO UPDATE END_INDEX!!!.
COMPUTE END_INDEX=.1394.

*CALULATE TIME ADJUSTMENT FACTOR.
COMPUTE TAF=END_INDEX/PRICE_INDEX.
GRAPH/SCATTER=MONTHS WITH TAF.
MEANS TAF BY MONTHS/CELLS=MEAN.

COMPUTE TASP=saleprice*TAF.
COMPUTE TASPPSF=TASP/sRESB_FLOORAREA.
DES saleprice TASP TAF TASPPSF.
FILTER OFF. 


*******************************************************************
BUILDING SIZE (SBLDSF) TRANSFORMATIONS. 
*******************************************************************

FREQUENCIES SRESB_STYLE.
FREQUENCIES sRESB_FLOORAREA.
MEANS sRESB_FLOORAREA BY SRESB_STYLE/CELLS MEAN MEDIAN MIN MAX RANGE.
*# IS MINIMUM.
*# IS MEDIAN.
*ENTER sRESB_FLOORAREA directly into the model.
*USE Log of sRESB_FLOORAREA.

*Use Log of sRESB_FLOORAREA with an intercept. 
 COMPUTE LNSBLDSF= LN(sRESB_FLOORAREA).
*Enter SBLSF with an intercept - SMALLEST BUILDING IN MASTER FILE.

*DON'T FORGET TO UPDATE INTERCEPT & MEDIAN.

 COMPUTE SBLDSFINT= (sRESB_FLOORAREA-432).
*USE log of SBLDSF with an intercept.
 COMPUTE LNSBLDSFINT = LN(sRESB_FLOORAREA-432).

*USE MEDIAN CENTERED SBLDSF.
 COMPUTE SBLDSFMED=(sRESB_FLOORAREA-1051).

*USE LOG OF MEDIAN CENTERED SBLDSF.
 COMPUTE LNSBLDSFMED=LN(sRESB_FLOORAREA-1051).
* Must transform negative numbers. 
 
 *USE LOG OF RATIO OF SBLDSF TO MEDIAN TO CALIBRATE SEPARATE SIZE CURVES FOR EACH STYLE
*TO calculate Medians for each groups of STYLE;Calculate the medians; Calculate Base Size, Size Ratio & LN SizeRatio
*TO create discrete variables of the LN_Ratio for each STYLE also Create discrete variables of the base Ratio for each STYLE for use in NLR.

RECODE SRESB_STYLE('SINGLE FAMILY' = 1)(ELSE = 0) INTO BSZ_SINGLE. 
MEANS sRESB_FLOORAREA BY BSZ_SINGLE/CELLS=COUNT MEDIAN MEAN MIN MAX. 
 * The median is: #. 

RECODE SRESB_STYLE('1/2 DUPLEX' = 1)(ELSE = 0) INTO BSZ_HALFDUPLEX. 
MEANS sRESB_FLOORAREA BY BSZ_HALFDUPLEX/CELLS=COUNT MEDIAN MEAN MIN MAX. 
* The median is: #. 

RECODE SRESB_STYLE('ROW HOUSE' = 1)(ELSE = 0) INTO BSZ_ROW.
MEANS sRESB_FLOORAREA BY BSZ_ROW/CELLS=COUNT MEDIAN MEAN MIN MAX. 
  * The median is: # . 


***************
* UPDATE RECODE USING MEDIANS BY STYLE.

RECODE SRESB_STYLE ('SINGLE FAMILY' =1056)('1/2 DUPLEX' =840) INTO BASE_BLDGSIZE. 
COMPUTE BASE_BLDGSIZE_RATIO=sRESB_FLOORAREA/BASE_BLDGSIZE. 
MEANS BASE_BLDGSIZE_RATIO BY SRESB_STYLE/CELLS=COUNT MEDIAN MEAN MIN MAX. 
COMPUTE LN_BASE_BLDGSIZE_RATIO=LN(BASE_BLDGSIZE_RATIO).
 
 * COMPUTE LN_SBLDSF_BSZ_ROW=0. 

 * IF (SRESB_STYLE='ROW HOUSE') LN_SBLDSF_BSZ_ROW=LN_BASE_BLDGSIZE_RATIO. 
COMPUTE LN_SBLDSF_BSZ_SINGLE=0. 
IF (SRESB_STYLE='SINGLE FAMILY') LN_SBLDSF_BSZ_SINGLE=LN_BASE_BLDGSIZE_RATIO. 
COMPUTE LN_SBLDSF_BSZ_HALFDUPLEX=0. 
IF (SRESB_STYLE='1/2 DUPLEX') LN_SBLDSF_BSZ_HALFDUPLEX=LN_BASE_BLDGSIZE_RATIO. 
 

***************

*LOT SIZE.
*CODE TO CALIBRATE SEPARATE SIZE CURVES FOR EACH STYLE
calculate Medians for each groups of STYLE; Calculate Base Size, Size Ratio & LN SizeRatio
create discrete variables of the LN_Ratio for each STYLE also Create discrete variables of the base Ratio for each STYLE for use in NLR.

RECODE SRESB_STYLE('ROW HOUSE' = 1)(ELSE = 0) INTO LSZ_ROW. 
MEANS sTOTALSQFT BY LSZ_ROW/CELLS=COUNT MEDIAN MEAN MIN MAX. 
 * The median is: #.
RECODE SRESB_STYLE('SINGLE FAMILY' = 1)(ELSE = 0) INTO LSZ_SINGLE. 
MEANS sTOTALSQFT BY LSZ_SINGLE/CELLS=COUNT MEDIAN MEAN MIN MAX. 
 * The median is: #.
RECODE SRESB_STYLE('1/2 DUPLEX' = 1)(ELSE = 0) INTO LSZ_HALFDUPLEX. 
MEANS sTOTALSQFT BY LSZ_HALFDUPLEX/CELLS=COUNT MEDIAN MEAN MIN MAX. 
 * The median is: #.
 
*DON'T FORGET TO UPDATE MEDIANS!.
RECODE SRESB_STYLE ('SINGLE FAMILY' =4599)('1/2 DUPLEX' =3180) INTO BASE_LOTSIZE. 
COMPUTE BASE_LOTSIZE_RATIO=sTOTALSQFT/BASE_LOTSIZE. 
MEANS BASE_LOTSIZE_RATIO BY SRESB_STYLE/CELLS=COUNT MEDIAN MEAN MIN MAX. 
COMPUTE LN_BASE_LOTSIZE_RATIO=LN(BASE_LOTSIZE_RATIO). 

*???????????????????????????????????????????
 *WHAT IS THIS FOR? IS IT BEING USED?
 
 * COMPUTE LN_LOTSF_LSZ_ROW=0. 
 * IF (SRESB_STYLE='ROW HOUSE') LN_LotSF_LSZ_ROW=LN_BASE_LOTSIZE_RATIO. 
 * COMPUTE LN_LotSF_LSZ_SINGLE=0. 
 * IF (SRESB_STYLE='SINGLE FAMILY') LN_LotSF_LSZ_SINGLE=LN_BASE_LOTSIZE_RATIO. 
 * COMPUTE LN_LotSF_LSZ_HALFDUPLEX=0. 
 * IF (SRESB_STYLE='1/2 DUPLEX') LN_LotSF_LSZ_HALFDUPLEX=LN_BASE_LOTSIZE_RATIO. 
*????????????????????????????????????.



***************
*LAND RATIO

COMPUTE LANDRATIO=sTOTALSQFT/BASE_LOTSIZE.
COMPUTE LANDRATIO2=LANDRATIO. 
IF (LANDRATIO>=.90 AND LANDRATIO<=1.10) LANDRATIO2=1.

*Use TASP if you have time adjustments in the model.
GRAPH/SCATTER=LANDRATIO2 WITH TASP BY SRESB_STYLE.
    
*GRAPH/SCATTER=LANDRATIO2 WITH PRICE BY SRESB_STYLE.
IF (SRESB_STYLE NE 'SINGLE FAMILY' AND LANDRATIO>3) LANDRATIO2=3.
IF (SRESB_STYLE='SINGLE FAMILY' AND LANDRATIO>4) LANDRATIO2=4.

COMPUTE LN_LANDRATIO=LN(LANDRATIO2).



*******************************************************************
*TEST MODEL WITHOUT ECFS.
*******************************************************************

COMPUTE LN_PRICE=LN(SALEPRICE).
COMPUTE LN_TASP=LN(TASP).

 REGRESSION 
  /STATISTICS COEFF OUTS R ANOVA 
  /CRITERIA=PIN(.05) POUT(.10) 
  /DEPENDENT LN_PRICE
  /METHOD=BACKWARD 
  LN_LANDRATIO LN_BASE_BLDGSIZE_RATIO
 ARTERIAL
SINGLE_FAMILY1STORY TO HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24.


*ADJ R2=.137.


***************
ECFs WITH 9+ SALES.
*use TASP if available. IF NOT, USE SALEPRICE.

FREQUENCIES ECF.

MEANS TASP BY ECF/CELLS=COUNT MEDIAN MEAN MIN MAX.
MEANS TASPPSF BY ECF/CELLS=COUNT MEDIAN MEAN MIN MAX.

* ECF 1R117 IS BASE.
RECODE ECF('1R101'=1)(ELSE=0) INTO ECF1R101.
RECODE ECF('1R102'=1)(ELSE=0) INTO ECF1R102.
RECODE ECF('1R103'=1)(ELSE=0) INTO ECF1R103.
RECODE ECF('1R104'=1)(ELSE=0) INTO ECF1R104.
RECODE ECF('1R105'=1)(ELSE=0) INTO ECF1R105.
RECODE ECF('1R106'=1)(ELSE=0) INTO ECF1R106.
RECODE ECF('1R107'=1)(ELSE=0) INTO ECF1R107.
RECODE ECF('1R108'=1)(ELSE=0) INTO ECF1R108.
RECODE ECF('1R109'=1)(ELSE=0) INTO ECF1R109.
RECODE ECF('1R110'=1)(ELSE=0) INTO ECF1R110.
RECODE ECF('1R111'=1)(ELSE=0) INTO ECF1R111.
RECODE ECF('1R112'=1)(ELSE=0) INTO ECF1R112.
RECODE ECF('1R113'=1)(ELSE=0) INTO ECF1R113.
RECODE ECF('1R114'=1)(ELSE=0) INTO ECF1R114.
RECODE ECF('1R115'=1)(ELSE=0) INTO ECF1R115.
RECODE ECF('1R116'=1)(ELSE=0) INTO ECF1R116.
RECODE ECF('1R117'=1)(ELSE=0) INTO ECF1R117.
RECODE ECF('1R118'=1)(ELSE=0) INTO ECF1R118.
RECODE ECF('1R119'=1)(ELSE=0) INTO ECF1R119.
RECODE ECF('1R120'=1)(ELSE=0) INTO ECF1R120.
RECODE ECF('1R121'=1)(ELSE=0) INTO ECF1R121.
RECODE ECF('1R122'=1)(ELSE=0) INTO ECF1R122.
RECODE ECF('1R123'=1)(ELSE=0) INTO ECF1R123.
RECODE ECF('1R124'=1)(ELSE=0) INTO ECF1R124.
RECODE ECF('1R125'=1)(ELSE=0) INTO ECF1R125.
RECODE ECF('1R126'=1)(ELSE=0) INTO ECF1R126.
RECODE ECF('1R127'=1)(ELSE=0) INTO ECF1R127.
RECODE ECF('1R128'=1)(ELSE=0) INTO ECF1R128.
RECODE ECF('1R129'=1)(ELSE=0) INTO ECF1R129.
RECODE ECF('1R130'=1)(ELSE=0) INTO ECF1R130.
RECODE ECF('1R131'=1)(ELSE=0) INTO ECF1R131.
RECODE ECF('1R132'=1)(ELSE=0) INTO ECF1R132.
RECODE ECF('1R133'=1)(ELSE=0) INTO ECF1R133.
RECODE ECF('1R134'=1)(ELSE=0) INTO ECF1R134.
RECODE ECF('1R135'=1)(ELSE=0) INTO ECF1R135.
RECODE ECF('1R136'=1)(ELSE=0) INTO ECF1R136.
RECODE ECF('1R137'=1)(ELSE=0) INTO ECF1R137.
RECODE ECF('2R201'=1)(ELSE=0) INTO ECF2R201.
RECODE ECF('2R202'=1)(ELSE=0) INTO ECF2R202.
RECODE ECF('2R203'=1)(ELSE=0) INTO ECF2R203.
RECODE ECF('2R204'=1)(ELSE=0) INTO ECF2R204.
RECODE ECF('2R205'=1)(ELSE=0) INTO ECF2R205.
RECODE ECF('2R206'=1)(ELSE=0) INTO ECF2R206.
RECODE ECF('2R207'=1)(ELSE=0) INTO ECF2R207.
RECODE ECF('2R208'=1)(ELSE=0) INTO ECF2R208.
RECODE ECF('2R209'=1)(ELSE=0) INTO ECF2R209.
RECODE ECF('2R210'=1)(ELSE=0) INTO ECF2R210.
RECODE ECF('2R211'=1)(ELSE=0) INTO ECF2R211.
RECODE ECF('2R212'=1)(ELSE=0) INTO ECF2R212.
RECODE ECF('2R213'=1)(ELSE=0) INTO ECF2R213.
RECODE ECF('2R214'=1)(ELSE=0) INTO ECF2R214.
RECODE ECF('2R215'=1)(ELSE=0) INTO ECF2R215.
RECODE ECF('2R216'=1)(ELSE=0) INTO ECF2R216.
RECODE ECF('2R217'=1)(ELSE=0) INTO ECF2R217.
RECODE ECF('2R218'=1)(ELSE=0) INTO ECF2R218.
RECODE ECF('2R219'=1)(ELSE=0) INTO ECF2R219.
RECODE ECF('2R220'=1)(ELSE=0) INTO ECF2R220.
RECODE ECF('2R221'=1)(ELSE=0) INTO ECF2R221.
RECODE ECF('2R222'=1)(ELSE=0) INTO ECF2R222.
RECODE ECF('2R223'=1)(ELSE=0) INTO ECF2R223.
RECODE ECF('2R224'=1)(ELSE=0) INTO ECF2R224.
RECODE ECF('2R225'=1)(ELSE=0) INTO ECF2R225.
RECODE ECF('2R226'=1)(ELSE=0) INTO ECF2R226.
RECODE ECF('2R227'=1)(ELSE=0) INTO ECF2R227.
RECODE ECF('2R228'=1)(ELSE=0) INTO ECF2R228.
RECODE ECF('2R229'=1)(ELSE=0) INTO ECF2R229.
RECODE ECF('2R230'=1)(ELSE=0) INTO ECF2R230.
RECODE ECF('3R301'=1)(ELSE=0) INTO ECF3R301.
RECODE ECF('3R302'=1)(ELSE=0) INTO ECF3R302.
RECODE ECF('3R303'=1)(ELSE=0) INTO ECF3R303.
RECODE ECF('3R304'=1)(ELSE=0) INTO ECF3R304.
RECODE ECF('3R305'=1)(ELSE=0) INTO ECF3R305.
RECODE ECF('3R306'=1)(ELSE=0) INTO ECF3R306.
RECODE ECF('3R307'=1)(ELSE=0) INTO ECF3R307.
RECODE ECF('3R308'=1)(ELSE=0) INTO ECF3R308.
RECODE ECF('3R309'=1)(ELSE=0) INTO ECF3R309.
RECODE ECF('3R310'=1)(ELSE=0) INTO ECF3R310.
RECODE ECF('3R311'=1)(ELSE=0) INTO ECF3R311.
RECODE ECF('3R312'=1)(ELSE=0) INTO ECF3R312.
RECODE ECF('3R313'=1)(ELSE=0) INTO ECF3R313.
RECODE ECF('3R314'=1)(ELSE=0) INTO ECF3R314.
RECODE ECF('3R315'=1)(ELSE=0) INTO ECF3R315.
RECODE ECF('3R316'=1)(ELSE=0) INTO ECF3R316.
RECODE ECF('3R317'=1)(ELSE=0) INTO ECF3R317.
RECODE ECF('3R318'=1)(ELSE=0) INTO ECF3R318.
RECODE ECF('3R319'=1)(ELSE=0) INTO ECF3R319.
RECODE ECF('3R320'=1)(ELSE=0) INTO ECF3R320.
RECODE ECF('3R321'=1)(ELSE=0) INTO ECF3R321.
RECODE ECF('3R322'=1)(ELSE=0) INTO ECF3R322.
RECODE ECF('3R323'=1)(ELSE=0) INTO ECF3R323.
RECODE ECF('3R324'=1)(ELSE=0) INTO ECF3R324.
RECODE ECF('3R325'=1)(ELSE=0) INTO ECF3R325.
RECODE ECF('3R326'=1)(ELSE=0) INTO ECF3R326.
RECODE ECF('4R401'=1)(ELSE=0) INTO ECF4R401.
RECODE ECF('4R402'=1)(ELSE=0) INTO ECF4R402.
RECODE ECF('4R403'=1)(ELSE=0) INTO ECF4R403.
RECODE ECF('4R404'=1)(ELSE=0) INTO ECF4R404.
RECODE ECF('4R405'=1)(ELSE=0) INTO ECF4R405.
RECODE ECF('4R406'=1)(ELSE=0) INTO ECF4R406.
RECODE ECF('4R407'=1)(ELSE=0) INTO ECF4R407.
RECODE ECF('4R408'=1)(ELSE=0) INTO ECF4R408.
RECODE ECF('4R409'=1)(ELSE=0) INTO ECF4R409.
RECODE ECF('4R410'=1)(ELSE=0) INTO ECF4R410.
RECODE ECF('4R411'=1)(ELSE=0) INTO ECF4R411.
RECODE ECF('4R412'=1)(ELSE=0) INTO ECF4R412.
RECODE ECF('4R413'=1)(ELSE=0) INTO ECF4R413.
RECODE ECF('4R414'=1)(ELSE=0) INTO ECF4R414.
RECODE ECF('4R415'=1)(ELSE=0) INTO ECF4R415.
RECODE ECF('4R416'=1)(ELSE=0) INTO ECF4R416.
RECODE ECF('4R417'=1)(ELSE=0) INTO ECF4R417.
RECODE ECF('4R418'=1)(ELSE=0) INTO ECF4R418.
RECODE ECF('4R419'=1)(ELSE=0) INTO ECF4R419.
RECODE ECF('4R421'=1)(ELSE=0) INTO ECF4R421.
RECODE ECF('4R422'=1)(ELSE=0) INTO ECF4R422. 
RECODE ECF('4R423'=1)(ELSE=0) INTO ECF4R423.
RECODE ECF('5R501'=1)(ELSE=0) INTO ECF5R501.
RECODE ECF('5R502'=1)(ELSE=0) INTO ECF5R502.
RECODE ECF('5R503'=1)(ELSE=0) INTO ECF5R503.
RECODE ECF('5R504'=1)(ELSE=0) INTO ECF5R504.
RECODE ECF('5R505'=1)(ELSE=0) INTO ECF5R505.
RECODE ECF('5R506'=1)(ELSE=0) INTO ECF5R506.
RECODE ECF('5R507'=1)(ELSE=0) INTO ECF5R507.
RECODE ECF('5R508'=1)(ELSE=0) INTO ECF5R508.
RECODE ECF('5R509'=1)(ELSE=0) INTO ECF5R509.
RECODE ECF('5R510'=1)(ELSE=0) INTO ECF5R510.
RECODE ECF('5R511'=1)(ELSE=0) INTO ECF5R511.
RECODE ECF('5R512'=1)(ELSE=0) INTO ECF5R512.
RECODE ECF('5R513'=1)(ELSE=0) INTO ECF5R513.
RECODE ECF('5R514'=1)(ELSE=0) INTO ECF5R514.
RECODE ECF('5R515'=1)(ELSE=0) INTO ECF5R515.
RECODE ECF('5R516'=1)(ELSE=0) INTO ECF5R516.
RECODE ECF('5R517'=1)(ELSE=0) INTO ECF5R517.
RECODE ECF('5R518'=1)(ELSE=0) INTO ECF5R518.
RECODE ECF('5R519'=1)(ELSE=0) INTO ECF5R519.
RECODE ECF('5R520'=1)(ELSE=0) INTO ECF5R520.
RECODE ECF('5R521'=1)(ELSE=0) INTO ECF5R521.
RECODE ECF('5R522'=1)(ELSE=0) INTO ECF5R522.
RECODE ECF('5R523'=1)(ELSE=0) INTO ECF5R523.
RECODE ECF('5R524'=1)(ELSE=0) INTO ECF5R524.
RECODE ECF('5R525'=1)(ELSE=0) INTO ECF5R525.
RECODE ECF('5R526'=1)(ELSE=0) INTO ECF5R526.
RECODE ECF('5R528'=1)(ELSE=0) INTO ECF5R528.
RECODE ECF('5R529'=1)(ELSE=0) INTO ECF5R529.
RECODE ECF('5R530'=1)(ELSE=0) INTO ECF5R530.
RECODE ECF('5R531'=1)(ELSE=0) INTO ECF5R531.
RECODE ECF('5R532'=1)(ELSE=0) INTO ECF5R532.
RECODE ECF('5R533'=1)(ELSE=0) INTO ECF5R533.
RECODE ECF('5R534'=1)(ELSE=0) INTO ECF5R534.
RECODE ECF('5R535'=1)(ELSE=0) INTO ECF5R535.
RECODE ECF('5R536'=1)(ELSE=0) INTO ECF5R536.
RECODE ECF('5R537'=1)(ELSE=0) INTO ECF5R537.
RECODE ECF('5r538'=1)(ELSE=0) INTO ECF5R538.
RECODE ECF('5R539'=1)(ELSE=0) INTO ECF5R539.
RECODE ECF('6R601'=1)(ELSE=0) INTO ECF6R601.
RECODE ECF('6R602'=1)(ELSE=0) INTO ECF6R602.
RECODE ECF('6R603'=1)(ELSE=0) INTO ECF6R603.
RECODE ECF('6R604'=1)(ELSE=0) INTO ECF6R604.
RECODE ECF('6R605'=1)(ELSE=0) INTO ECF6R605.
RECODE ECF('6R606'=1)(ELSE=0) INTO ECF6R606.
RECODE ECF('6R607'=1)(ELSE=0) INTO ECF6R607.
RECODE ECF('6R608'=1)(ELSE=0) INTO ECF6R608.
RECODE ECF('6R609'=1)(ELSE=0) INTO ECF6R609.
RECODE ECF('6R611'=1)(ELSE=0) INTO ECF6R611.
RECODE ECF('6R612'=1)(ELSE=0) INTO ECF6R612.
RECODE ECF('6R613'=1)(ELSE=0) INTO ECF6R613.
RECODE ECF('6R614'=1)(ELSE=0) INTO ECF6R614.
RECODE ECF('6R615'=1)(ELSE=0) INTO ECF6R615.
RECODE ECF('6R616'=1)(ELSE=0) INTO ECF6R616.
RECODE ECF('6R617'=1)(ELSE=0) INTO ECF6R617.
RECODE ECF('6R618'=1)(ELSE=0) INTO ECF6R618.
RECODE ECF('6R619'=1)(ELSE=0) INTO ECF6R619.
RECODE ECF('6R620'=1)(ELSE=0) INTO ECF6R620.
RECODE ECF('7R701'=1)(ELSE=0) INTO ECF7R701.
RECODE ECF('7R702'=1)(ELSE=0) INTO ECF7R702.
RECODE ECF('7R703'=1)(ELSE=0) INTO ECF7R703.
RECODE ECF('7R704'=1)(ELSE=0) INTO ECF7R704.
RECODE ECF('7R705'=1)(ELSE=0) INTO ECF7R705.
RECODE ECF('7R706'=1)(ELSE=0) INTO ECF7R706.
RECODE ECF('7R707'=1)(ELSE=0) INTO ECF7R707.
RECODE ECF('7R708'=1)(ELSE=0) INTO ECF7R708.
RECODE ECF('7R709'=1)(ELSE=0) INTO ECF7R709.
RECODE ECF('7R710'=1)(ELSE=0) INTO ECF7R710.
RECODE ECF('7R711'=1)(ELSE=0) INTO ECF7R711.
RECODE ECF('7R712'=1)(ELSE=0) INTO ECF7R712.
RECODE ECF('7R713'=1)(ELSE=0) INTO ECF7R713.
RECODE ECF('7R714'=1)(ELSE=0) INTO ECF7R714.
RECODE ECF('7R715'=1)(ELSE=0) INTO ECF7R715.
RECODE ECF('7R716'=1)(ELSE=0) INTO ECF7R716.
RECODE ECF('7R717'=1)(ELSE=0) INTO ECF7R717.
RECODE ECF('7R718'=1)(ELSE=0) INTO ECF7R718.
RECODE ECF('7R719'=1)(ELSE=0) INTO ECF7R719.
RECODE ECF('7R720'=1)(ELSE=0) INTO ECF7R720.
RECODE ECF('7R721'=1)(ELSE=0) INTO ECF7R721.
RECODE ECF('7R722'=1)(ELSE=0) INTO ECF7R722.
RECODE ECF('7R723'=1)(ELSE=0) INTO ECF7R723.
RECODE ECF('7R724'=1)(ELSE=0) INTO ECF7R724.


* Line for regression 
ECF1R101 TO ECF7R724.
 * FILTER OFF.



*******************************************************************
*SPATIALS
*******************************************************************
*UNUSED AT THIS TIME.

*SET UP THE SPATIAL VARIABLES AND 
ADD THE SPATIAL VARIABLES.TO THE FINAL REGRESSION.

 
* --- COMPUTE DISTANCE VARIABLES AS USED IN THE NLR MODEL. AND 
 
* --- TAKING LOGS OF DISTANCE VARS SO CAN SERVE AS MULTIPLIERS IN MULTIPLICATIVE MODEL. 
  
 * COMPUTE DIST_PARK = Prk_DSq_ED. 
 * COMPUTE DIST_RAIL = Rail_NN5_ED. 
 
 * COMPUTE DIST_PARK_RATIO = DIST_PARK/MED_DIST_PARK. 
 * COMPUTE DIST_RAIL_RATIO = DIST_RAIL/MED_DIST_RAIL. 
 * COMPUTE LN_DIST_PARK_RATIO = LN(DIST_PARK_RATIO).  
 * COMPUTE LN_DIST_RAIL_RATIO = LN(DIST_RAIL_RATIO). 
  
*COPY NEEDED SPATIAL VARIABLES 
* LN_DIST_PARK_RATIO  LN_DIST_RAIL_RATIO . 
 


*******************************************************************
*CORRELATIONS
*******************************************************************

*PEARSON COEFFICIENTS CLOSER TO 0 IS BETTER CAREFULLY CONSIDER IF >.5.
 CORRELATIONS 
 LN_LANDRATIO LN_BASE_BLDGSIZE_RATIO
 ARTERIAL
SINGLE_FAMILY1STORY TO  HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24.
*CHECK IF COLLIN VIF GETS ABOVE 5.(VIF=1/TOL).



*******************************************************************
*BASE MODEL
*******************************************************************

REGRESSION
    /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
    /DESCRIPTIVES MEAN STDDEV CORR SIG N 
    /CRITERIA=PIN(.05) POUT(.10)
    /DEPENDENT LN_PRICE
    /METHOD=BACKWARD
 LN_LANDRATIO LN_BASE_BLDGSIZE_RATIO
 ARTERIAL
SINGLE_FAMILY1STORY TO  HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24
    /SCATTERPLOT=(*ZRESID ,*ZPRED) (*COOK,*SDRESID) (*LEVER, *SDRESID) 
    /RESIDUALS DURBIN HISTOGRAM(ZRESID SDRESID LEVER) NORMPROB(ZRESID SDRESID) OUTLIERS(ZRESID SDRESID, LEVER, COOK)
    /SAVE=PRED, MAHAL, SDRESID, COOK, ZRESID, LEVER, COVRATIO, MCIN.

COMPUTE ESP1=EXP(PRE_1).
COMPUTE RATIO1=ESP1/SALEPRICE.
RATIO STATS ESP1 WITH SALEPRICE BY ECF/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY SRESB_STYLE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY SCOND/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY SIZE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY ERABUILT/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY  LN_GARAGESPACES/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY sYear/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY FIREPLACE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
RATIO STATS ESP1 WITH SALEPRICE BY PRICECLASS/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD COD.
GRAPH/SCATTER=SALEPRICE WITH ESP1 BY SRESB_STYLE.
GRAPH/SCATTER=ESP1 WITH RATIO1.
GRAPH/HIST=RATIO1.

COMPUTE WITHIN10_1=0.
IF (RATIO1 LE 1.1) AND (RATIO1 GE .9) WITHIN10_1=1.
COMPUTE WITHIN20_1=0.
IF (RATIO1 LE 1.2) AND (RATIO1 GE .8) WITHIN20_1=1.
COMPUTE WITHIN50_1=0.
IF (RATIO1 LE 1.5) AND (RATIO1 GE .5) WITHIN50_1=1.
FREQ WITHIN10_1 WITHIN20_1 WITHIN50_1.

*Adjusted R Square: 0.283 Median: 0.984 Price Related Differential: 1.210 Coefficient of Dispersion: 0.399
WITHIN 10: 11.1% WITHIN 20: 23.1% WITHIN 50: 57.1%


*******************************************************************
*REGRESSION WITH OUTLIERS INFLUENCE REMOVED.
*******************************************************************

FILTER OFF.

COMPUTE IN=1.

*OUTLIER REMOVAL BY COOKS AND STUDENTIZED RESIDUALS.
*COO_1 IS COOK'S DISTANCE FROM BASE REGRESSION RUN
*SDR_1 IS STUDENTIZED DELETED RESIDUAL FROM BASE REGRESSION RUN

*MAKE SURE YOU UPDATE NUMBER OF TOTAL CASES.!!!!!!.
IF (COO_1>(4/3044)) IN=0.
IF (ABS(SDR_1)>2) IN=0.
FREQ IN.
*# CASES #%.

*FILTER TO RUN ON NON-OUTLIERS WITHOUT REMOVING THEM FROM DATA.
FILTER BY IN.

REGRESSION
    /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
    /DESCRIPTIVES MEAN STDDEV CORR SIG N 
    /CRITERIA=PIN(.05) POUT(.10)
    /DEPENDENT LN_PRICE
    /METHOD=BACKWARD
 LN_LANDRATIO LN_BASE_BLDGSIZE_RATIO
 ARTERIAL
SINGLE_FAMILY1STORY TO  HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
MONTHS_1TO9 MONTHS_10TO16 MONTHS_17TO24
    /SCATTERPLOT=(*ZRESID ,*ZPRED) (*COOK,*SDRESID) (*LEVER, *SDRESID) 
    /RESIDUALS DURBIN HISTOGRAM(ZRESID SDRESID LEVER) NORMPROB(ZRESID SDRESID) OUTLIERS(ZRESID SDRESID, LEVER, COOK)
    /SAVE=PRED, MAHAL, SDRESID, COOK, ZRESID, LEVER, COVRATIO, MCIN.

COMPUTE ESP2=EXP(PRE_2).
COMPUTE RATIO2=ESP2/SALEPRICE.
RATIO STATS ESP2 WITH SALEPRICE BY ECF/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY SCOND/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY SIZE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY PRICECLASS/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY ERABUILT/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY  LN_GARAGESPACES/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY sYear/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY FIREPLACE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP2 WITH SALEPRICE BY SRESB_STYLE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
GRAPH/SCATTER=SALEPRICE WITH ESP2 BY SRESB_STYLE.
GRAPH/SCATTER=ESP2 WITH RATIO2.
GRAPH/HIST=RATIO2.

COMPUTE WITHIN10_2=0.
IF (RATIO2 LE 1.1) AND (RATIO2 GE .9) WITHIN10_2=1.
COMPUTE WITHIN20_2=0.
IF (RATIO2 LE 1.2) AND (RATIO2 GE .8) WITHIN20_2=1.
COMPUTE WITHIN50_2=0.
IF (RATIO2 LE 1.5) AND (RATIO2 GE .5) WITHIN50_2=1.
FREQ WITHIN10_2 WITHIN20_2 WITHIN50_2.

*Adjusted R Square: 0.283 Median: 0.984 Price Related Differential: 1.210 Coefficient of Dispersion: 0.399
WITHIN 10: 11.1% WITHIN 20: 23.1% WITHIN 50: 57.1%
*Adjusted R Square: 0.311 Median: 0.996 Price Related Differential: 1.161 PRB -.512 Coefficient of Dispersion: 0.345
WITHIN 10: 12.3% WITHIN 20: 25.3% WITHIN 50: 58.3%


*******************************************************************
*RECALIBRATE TIME ADJUSTMENTS.
*******************************************************************
*COPY THE RATES FOR ANY SIGNIFICANT TIME PERIODS FROM THE LAST REGRESSION INTO THE SECTION BELOW. 
*DELETE ANY TIME PERIODS THAT DO NOT APPLY. 
*SOLVING FOR TIME ADJUSTED SP OR TIME ADJUSTED SPPSF TAKES THE TIME VARIABLES OUT OF THE MODEL, WHICH ALLOWS 
USE TO CREATE COEFFICIENTS THAT CAN BE APPLIED TO PROPERTIES THAT DID NOT SELL.

COMPUTE RATE1 =0.
COMPUTE RATE2 =0.008163.
COMPUTE RATE3 = 0.016002.

* MAKE SURE YOU UPDATE TIME VARIABLES FROM INITIAL .
COMPUTE PRICE_INDEX = (1+RATE1)**MONTHS_1TO9* (1+RATE2)**MONTHS_10TO16* (1+RATE3)**MONTHS_17TO24.
GRAPH/SCATTER=MONTHS WITH PRICE_INDEX.

*TIME ADJUSTMENT FACTORS.
MEANS PRICE_INDEX BY MONTHS/CELLS=MEAN.

*RECORD THE VALUE FOR LAST MONTH (TARGET MONTH) AS END_INDEX.
*DON'T FORGET TO UPDATE END_INDEX!!!.
COMPUTE END_INDEX=1.2019.
COMPUTE TAF=END_INDEX/PRICE_INDEX.
GRAPH/SCATTER=MONTHS WITH TAF.
MEANS TAF BY MONTHS/CELLS=MEAN.

COMPUTE TASP=saleprice*TAF.
COMPUTE TASPPSF=TASP/sRESB_FLOORAREA.
DES saleprice TASP TAF TASPPSF.


*******************************************************************
*REGRESSION WITH RECALIBRATED TIME ADJUSTMENTS.
*******************************************************************

*CHANGE DEPENDENT VARIABLE TO LN_TASP.
*REMOVE TIME VARIABLES FROM MODEL.

COMPUTE LN_TASP=LN(TASP).

FREQUENCIES IN.
FILTER BY IN.

REGRESSION
    /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
    /DESCRIPTIVES MEAN STDDEV CORR SIG N 
    /CRITERIA=PIN(.05) POUT(.10)
    /DEPENDENT LN_TASP
    /METHOD=BACKWARD
 LN_LANDRATIO LN_BASE_BLDGSIZE_RATIO
 ARTERIAL
SINGLE_FAMILY1STORY TO  HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
 LN_GARAGESPACES FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
    /SCATTERPLOT=(*ZRESID ,*ZPRED) (*COOK,*SDRESID) (*LEVER, *SDRESID) 
    /RESIDUALS DURBIN HISTOGRAM(ZRESID SDRESID LEVER) NORMPROB(ZRESID SDRESID) OUTLIERS(ZRESID SDRESID, LEVER, COOK)
    /SAVE=PRED, MAHAL, SDRESID, COOK, ZRESID, LEVER, COVRATIO, MCIN.

COMPUTE ESP3=EXP(PRE_3).
COMPUTE RATIO3=ESP3/TASP.
RATIO STATS ESP3 WITH TASP BY ECF/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY SCOND/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY SIZE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY PRICECLASS/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY ERABUILT/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY  LN_GARAGESPACES/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY sYear/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY FIREPLACE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP3 WITH TASP BY SRESB_STYLE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
GRAPH/SCATTER=TASP WITH ESP3 BY SRESB_STYLE.
GRAPH/SCATTER=ESP3 WITH RATIO3.
GRAPH/HIST=RATIO3.

COMPUTE WITHIN10_3=0.
IF (RATIO3 LE 1.1) AND (RATIO3 GE .9) WITHIN10_3=1.
COMPUTE WITHIN20_3=0.
IF (RATIO3 LE 1.2) AND (RATIO3 GE .8) WITHIN20_3=1.
COMPUTE WITHIN50_3=0.
IF (RATIO3 LE 1.5) AND (RATIO3 GE .5) WITHIN50_3=1.
FREQ WITHIN10_3 WITHIN20_3 WITHIN50_3.


*Adjusted R Square: 0.283 Median: 0.984 Price Related Differential: 1.210 Coefficient of Dispersion: 0.399
WITHIN 10: 11.1% WITHIN 20: 23.1% WITHIN 50: 57.1%
*Adjusted R Square: 0.311 Median: 0.996 Price Related Differential: 1.161 PRB -.512 Coefficient of Dispersion: 0.345
WITHIN 10: 12.3% WITHIN 20: 25.3% WITHIN 50: 58.3%
*Adjusted R Square: 0.297 Median: 0.996 Price Related Differential: 1.161 PRB -.535 Coefficient of Dispersion: 0.344
WITHIN 10: 12.3% WITHIN 20: 25.3% WITHIN 50: 58.3%



*******************************************************************
*RECALIBRATED MODEL WITH DIFFERENT GARAGE AND BUILDING SIZE VARIABLES.
*******************************************************************
    
*USE BINARY GARAGE VARIABLE INSTEAD OF GARAGE SPACES
*USE LNSBLDSFINT (LOG OF BUILDING SIZE WITH INTERCEPT) INSTEAD OF LN_BASE_BLDGSIZE_RATIO.

REGRESSION
    /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
    /DESCRIPTIVES MEAN STDDEV CORR SIG N 
    /CRITERIA=PIN(.05) POUT(.10)
    /DEPENDENT LN_TASP
    /METHOD=BACKWARD
   LN_LANDRATIO LNSBLDSFINT
   ARTERIAL
SINGLE_FAMILY1STORY TO HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
GARAGE FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
    /SCATTERPLOT=(*ZRESID ,*ZPRED) (*COOK,*SDRESID) (*LEVER, *SDRESID) 
    /RESIDUALS DURBIN HISTOGRAM(ZRESID SDRESID LEVER) NORMPROB(ZRESID SDRESID) OUTLIERS(ZRESID SDRESID, LEVER, COOK)
    /SAVE=PRED, MAHAL, SDRESID, COOK, ZRESID, LEVER, COVRATIO, MCIN.

COMPUTE ESP4=EXP(PRE_4).
COMPUTE RATIO4=ESP4/TASP.
RATIO STATS ESP4 WITH TASP BY ECF/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY SCOND/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY SIZE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY PRICECLASS/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY ERABUILT/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY  LN_GARAGESPACES/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY sYear/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY FIREPLACE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
RATIO STATS ESP4 WITH TASP BY SRESB_STYLE/PRINT=MEDIAN MEAN WGTMEAN MIN MAX PRD PRB COD.
GRAPH/SCATTER=TASP WITH ESP4 BY SRESB_STYLE.
GRAPH/SCATTER=ESP4 WITH RATIO4.
GRAPH/HIST=RATIO4.

COMPUTE WITHIN10_4=0.
IF (RATIO4 LE 1.1) AND (RATIO4 GE .9) WITHIN10_4=1.
COMPUTE WITHIN20_4=0.
IF (RATIO4 LE 1.2) AND (RATIO4 GE .8) WITHIN20_4=1.
COMPUTE WITHIN50_4=0.
IF (RATIO4 LE 1.5) AND (RATIO4 GE .5) WITHIN50_4=1.
FREQ WITHIN10_4 WITHIN20_4 WITHIN50_4.


*Adjusted R Square: 0.283 Median: 0.984 Price Related Differential: 1.210 Coefficient of Dispersion: 0.399
WITHIN 10: 11.1% WITHIN 20: 23.1% WITHIN 50: 57.1%
*Adjusted R Square: 0.311 Median: 0.996 Price Related Differential: 1.161 PRB -.512 Coefficient of Dispersion: 0.345
WITHIN 10: 12.3% WITHIN 20: 25.3% WITHIN 50: 58.3%
*Adjusted R Square: 0.297 Median: 0.996 Price Related Differential: 1.161 PRB -.535 Coefficient of Dispersion: 0.344
WITHIN 10: 12.3% WITHIN 20: 25.3% WITHIN 50: 58.3%
*Adjusted R Square: 0.330 Median: 0.989 Price Related Differential: 1.186 PRB -.510 Coefficient of Dispersion: 0.373
WITHIN 10: 16.0% WITHIN 20: 32.7% WITHIN 50: 76.9%


******************************************************************
*To export saved model.
*IF NOT EXPORTING MODEL, SKIP TO BOTTOM SECTION.
******************************************************************.

REGRESSION
     /MATRIX=OUT('G:\MODELING_DATA\Models\2022-2024 Sales\CCD1 - Grandmont Area\GrandmontECFs.MATRIX.SAV')
    /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
    /DESCRIPTIVES MEAN STDDEV CORR SIG N 
    /CRITERIA=PIN(.05) POUT(.10)
    /DEPENDENT LN_TASP
    /METHOD=BACKWARD
   LN_LANDRATIO LNSBLDSFINT
   ARTERIAL
SINGLE_FAMILY2STORY TO HALF_DUPLEX2STORY
 SMALLEST TO LARGEST
 TWO_PLUS_BATHS TO POWDER_ROOM
 GOOD TO VERY_POOR_UNSOUND
 QABOVE_AVG TO QBELOW_AVG
 YB_PRE_1929 TO YB_POST_1961
 CRAWL SLAB
GARAGE FIREPLACE
 HOT_WATER TO CENTRAL_AIR
CLUSTER2 TO CLUSTER55
 /SAVE=PRED MCIN
 /OUTFILE=model('G:\MODELING_DATA\Models\2022-2024 Sales\CCD1 - Grandmont Area\GrandmontECFs.xml').

FILTER OFF.

******************************************************************
* CONVERT LOG PREDICTIONS TO DOLLARS.
******************************************************************
COMPUTE MODMV=EXP(PRE_4).

******************************************************************
* CREATE CHARTS OF TASP AND TASPPSF BY ECF FROM THE FINAL MODEL.
******************************************************************

MEANS TASP BY ECF/CELLS=COUNT MEDIAN MEAN MIN MAX.
MEANS TASPPSF BY ECF/CELLS=COUNT MEDIAN MEAN MIN MAX.




